config/routes.rb
Fina::Application.routes.draw do
  devise_for :users
  resources :links
  resources :articles
  resources :pins
  resources :users
  resources :events

  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'
  get 'communalsparks' => 'pages#communalsparks'
  get 'sharesomething'=> 'pages#sharesomething'
  get 'happenings'=> 'pages#happenings'

  root :to => 'pages#home'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url 

  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
							content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
							size: { less_than: 5.megabytes }
  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}
  

	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super 
	end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

 <%= f.input :image, label: "Upload an image" %> 
 <%= f.input :image_remote_url, label: "Enter a URL" %> 
 <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-inverse" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box"> 
  <%= link_to (image_tag pin.image(:medium)), pin %>
  <p class="description">
    <%= pin.description %>
  </p>
  <p>
    <strong>
      Posted by <%= link_to pin.user.name, pin.user %>
    </strong>
  </p>
  <% if current_user == pin.user %>
    <%= link_to 'Edit', edit_pin_path(pin) %>
    <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins">
  <%= render @pins %>
</div> 

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class= "span6 offset3">
		<div class= "well">
			<%= image_tag @pin.image %> 
			<p> 
				<%= @pin.description %>
			</p>
			<p>
				<%= @pin.user.name %>
			</p>
			<% if current_user == @pin.user %> 
			<%= link_to 'Edit', edit_pin_path(@pin) %> 
			<% end %> 
			<%= link_to 'Back', communalsparks_path %> 
		</div>
	</div>
</div>	