config/routes.rb
Fina::Application.routes.draw do
  devise_for :users
  resources :links
  resources :articles
  resources :pins
  resources :users
  resources :events

  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'
  get 'communalsparks' => 'pages#communalsparks'
  get 'sharesomething'=> 'pages#sharesomething'
  get 'happenings'=> 'pages#happenings'

  root :to => 'pages#home'

  

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :url, :user_id, :user_name

  belongs_to :user
  validates :user_id, presence: true 
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_filter :authenticate_user!, except: [:index]
  # GET /links
  # GET /links.json
  def index
    @links = Link.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = current_user.links.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = current_user.links.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = current_user.links.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = current_user.links.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= simple_form_for(@link, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :url %>
    <%= f.input :description, as: :text, input_html: { rows: "6" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-inverse" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div class="box"> 
  <p>
    <strong>
      <%= link.description %>
    </strong>
  </p>
  <p>
    <%= link_to "Explore Link", link.url, :target => "_blank" %>
  </p>
  <p>
    Posted by <%= link_to link.user.name, link.user %>
  </p>
  <% if current_user == link.user %>
    <%= link_to 'Edit', edit_link_path(link) %>
    <%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Links</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
   </tr>
  </thead>

  <tbody>
    <%= render @links %>
  </tbody>
</table>


<br />

<%= link_to 'New Links', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<div class="row">
	<div class= "span6 offset3">
		<div class= "well">
			
			<p>
				<%= @link.description %>
			</p>
			<p>
				<%= link_to "Explore Link", @link.url %>
			</p>
			<p>
				<%= @link.user.name %>
			</p>

			<% if current_user == @link.user %>
			<%= link_to 'Edit', edit_link_path(@link) %> |
			<% end %>
			<%= link_to 'Back', communalsparks_path %>

		</div>
	</div>
</div>	