config/routes.rb
Fina::Application.routes.draw do
  devise_for :users
  resources :links
  resources :articles
  resources :pins
  resources :users
  resources :events

  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'
  get 'communalsparks' => 'pages#communalsparks'
  get 'sharesomething'=> 'pages#sharesomething'
  get 'happenings'=> 'pages#happenings'

  root :to => 'pages#home'

  

end

app/views/layouts/_footer.html.erb
<div class="footer">
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">fina MIAMI</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class ="nav">
      		<li><%= link_to "Home", root_path %></li>
      		<li><%= link_to "About", about_path %> </li>
          <li><%= link_to "Gallery", users_path %></li>
    		</ul>
    		<ul class="nav pull-right">
          <% if user_signed_in? %>

            <li><%= link_to "Happenings", events_path %></li>
            <li><%= link_to "Sparks", communalsparks_path %></li>
            <li><%= link_to "Share", sharesomething_path %></li>
            <li><%= link_to "Modifications", edit_user_path(current_user) %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Dive Deeper', new_user_session_path %></li>
          <% end %>
    		</ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Fina</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
    <%# image_tag("fina.png", :size => "280x130") %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>